name: covasim_schools CI workflow
on: [pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: [ '3.8' ]
    name: Install and test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install covasim_schools
        run: python setup.py develop
      - name: Run tests
        working-directory: ./tests
        run: |
          pip install pytest
          pytest test_*.py --durations=0 # Run actual tests
