name: covasim_schools CI workflow
on: [pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: [ '3.8' ]

    name: Install and test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Checkout SynthPops repo
        uses: actions/checkout@v2
        with:
          repository: InstituteforDiseaseModeling/synthpops
          path: synthpops

      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      
      - name: Install covasim
        run: pip install covasim
      
      - name: Install synthpops
        working-directory: synthpops
        run: python setup.py develop
      
      - name: Install covasim_schools
        run: python setup.py develop
      
      - name: Install pytest
        run: pip install pytest
      
      - name: Run tests
        working-directory: ./tests
        run: pytest test_*.py --durations=0 # Run actual tests
